'use strict';
const STORAGE_KEY = 'ayun-irlanda-v1';
const TARGET_DATE = new Date(2026, 10, 2);
const HABITS = [
  { id:'bed', icon:'🛏️', name:'Hacer la cama', detail:'Un inicio simple para ordenar el día.' },
  { id:'vitaminD', icon:'☀️', name:'Vitamina D', detail:'Marca solo tu pauta habitual.' },
  { id:'iron', icon:'🩷', name:'Hierro', detail:'Solo registra tu pauta habitual.' },
  { id:'contraceptive', icon:'🌙', name:'Anticonceptivo', detail:'Seguimiento, sin dosis ni horarios.' },
  { id:'water', icon:'💧', name:'Agua', detail:'Meta personal: 2 litros.' },
  { id:'english', icon:'🇬🇧', name:'Leer algo en inglés', detail:'Aunque sea poco: exposición diaria.' }
];
const TRAININGS = [
  { id:'bike', icon:'🚲', name:'Bicicleta', goal:4 },
  { id:'strength', icon:'🏋️‍♀️', name:'Fuerza / pesas', goal:3 }
];
const MESSAGES = {
  start:[['Vamos paso a paso.','No tienes que hacerlo todo de una. Empieza por una cosa pequeña.'],['Hoy también cuenta.','Una acción amable contigo misma ya cambia el tono del día.'],['Partamos suave.','Elige una de tus seis esenciales y déjala lista.']],
  early:[['Bien, ya empezaste.','No busquemos perfección: mantengamos el movimiento.'],['Ese primer paso importa.','Haz una más antes de que el día se llene de ruido.'],['Vas tomando ritmo.','Una cosa a la vez y sin apurarte.']],
  middle:[['Vas bien.','Ya hiciste bastante para que hoy tenga forma. Sigue con calma.'],['Mitad del camino.','Ahora cuida la energía y cierra lo importante.'],['Se nota la constancia.','No necesitas hacerlo perfecto para hacerlo bien.']],
  almost:[['Te queda muy poquito.','Cierra esa última esencial y suelta el día tranquila.'],['Una más.','No por obligación: por la satisfacción de haber cumplido contigo.'],['Estás a un paso.','Haz la que falta y después descansa.']],
  complete:[['Día cerrado.','Cumpliste contigo. No necesitas hacer más para que hoy valga.'],['Seis de seis.','Quédate con esa sensación: constante, no perfecta.'],['Hoy te cuidaste.','Mañana empezamos de nuevo, sin deuda y sin presión.']]
};
let state = loadState();
let currentDate = AyunCore.dateKey();
let calendarDate = new Date();
let selectedCalendarDate = null;
let undoSnapshot = null;
let toastTimer = null;
let pendingWorker = null;

function emptyState(){return{version:1,days:{},meta:{lastOpened:null,lastBackupAt:null}}}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!raw||typeof raw!=='object')return emptyState();const clean=emptyState();Object.entries(raw.days||{}).forEach(([k,v])=>{if(/^\d{4}-\d{2}-\d{2}$/.test(k))clean.days[k]=AyunCore.normalizeDay(v)});clean.meta={lastOpened:raw.meta?.lastOpened||null,lastBackupAt:raw.meta?.lastBackupAt||null};return clean}catch{return emptyState()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function day(key=currentDate,create=true){if(!state.days[key]&&create)state.days[key]=AyunCore.emptyDay();return state.days[key]}
function cloneState(){return JSON.parse(JSON.stringify(state))}
function withUndo(message,fn){undoSnapshot=cloneState();fn();save();renderAll();showToast(message,true)}
function showToast(message,undo=false){const el=document.querySelector('#toast');document.querySelector('#toast-message').textContent=message;document.querySelector('#undo-button').hidden=!undo;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function seededIndex(key,max){let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)%max}
function contextFor(record){const n=AyunCore.completedCount(record);if(n===6)return'complete';if(n===5)return'almost';if(n>=3)return'middle';if(n>=1)return'early';return'start'}
function messageFor(record){const ctx=contextFor(record);const list=MESSAGES[ctx];return list[seededIndex(`${currentDate}-${ctx}`,list.length)]}
function totalWins(){return Object.values(state.days).filter(AyunCore.dayWon).length}
function formatToday(){return new Date().toLocaleDateString('es-CL',{weekday:'short',day:'numeric',month:'short'})}
function weekRange(){const s=AyunCore.startOfWeek();const e=new Date(s);e.setDate(e.getDate()+6);return`${s.getDate()}–${e.getDate()} ${e.toLocaleDateString('es-CL',{month:'short'})}`}
function renderToday(){
  const record=day(); const count=AyunCore.completedCount(record); const percent=AyunCore.dayPercent(record); const xp=AyunCore.totalDayXp(record);
  document.querySelector('#today-date').textContent=formatToday();document.querySelector('#daily-percent').textContent=`${percent}%`;document.querySelector('#habit-count').textContent=`${count}/6`;document.querySelector('#days-left').textContent=AyunCore.daysUntil(TARGET_DATE);document.querySelector('#streak').textContent=AyunCore.consecutiveWonDays(state.days,currentDate);document.querySelector('#xp-today').textContent=xp;document.querySelector('#week-range').textContent=weekRange();
  const circumference=2*Math.PI*50;document.querySelector('#ring-value').style.strokeDashoffset=String(circumference*(1-percent/100));
  const [title,msg]=messageFor(record);document.querySelector('#ayun-title').textContent=title;document.querySelector('#ayun-message').textContent=msg;
  document.querySelector('#habit-list').innerHTML=HABITS.map(h=>{const done=Boolean(record.habits?.[h.id]);return`<button class="habit-card ${done?'done':''}" data-habit="${h.id}" aria-pressed="${done}"><span class="icon">${h.icon}</span><span class="habit-copy"><strong>${h.name}</strong><small>${h.detail}</small></span><span class="heart">${done?'♥':'♡'}</span></button>`}).join('');
  document.querySelectorAll('[data-habit]').forEach(btn=>btn.addEventListener('click',()=>withUndo(btn.classList.contains('done')?'Esencial desmarcada':'Esencial lista ♥',()=>{day().habits[btn.dataset.habit]=!Boolean(day().habits[btn.dataset.habit])})));
  document.querySelector('#training-list').innerHTML=TRAININGS.map(t=>{const done=record.trainings.includes(t.id);const countWeek=AyunCore.weeklyTrainingCount(state.days,t.id);return`<article class="training-card"><div class="training-top"><span>${t.icon}</span><div class="training-copy"><strong>${t.name}</strong><small>${countWeek} de ${t.goal} esta semana</small></div></div><div class="mini-bar"><span style="width:${Math.min(100,countWeek/t.goal*100)}%"></span></div><button class="training-toggle ${done?'done':''}" data-training="${t.id}">${done?'Hecho hoy ♥':'Registrar hoy'}</button></article>`}).join('');
  document.querySelectorAll('[data-training]').forEach(btn=>btn.addEventListener('click',()=>withUndo(btn.classList.contains('done')?'Sesión quitada':'Sesión registrada ♥',()=>{const list=day().trainings;day().trainings=list.includes(btn.dataset.training)?list.filter(x=>x!==btn.dataset.training):[...list,btn.dataset.training]})));
  document.querySelectorAll('[data-food]').forEach(btn=>btn.classList.toggle('active',btn.dataset.food===record.food));
  document.querySelectorAll('[data-mood]').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.mood)===record.mood));
  document.querySelector('#mood-note').value=record.moodNote||'';document.querySelector('#reflection').value=record.reflection||'';
}
function renderProgress(){const xp=AyunCore.totalXp(state.days);const lvl=AyunCore.levelFromXp(xp);document.querySelector('#metric-wins').textContent=totalWins();document.querySelector('#metric-best').textContent=AyunCore.bestStreak(state.days);document.querySelector('#metric-xp').textContent=xp;document.querySelector('#metric-level').textContent=lvl.level;document.querySelector('#level-copy').textContent=`Nivel ${lvl.level}`;document.querySelector('#level-next').textContent=`${lvl.next-lvl.current} XP para el siguiente`;document.querySelector('#level-bar').style.width=`${lvl.percent}%`;document.querySelector('#progress-training').innerHTML=TRAININGS.map(t=>`<div class="training-progress-row"><strong>${t.icon} ${t.name}</strong><span>${AyunCore.weeklyTrainingCount(state.days,t.id)} / ${t.goal}</span></div>`).join('');document.querySelector('#food-days').textContent=Object.values(state.days).filter(d=>d.food).length;document.querySelector('#mood-days').textContent=Object.values(state.days).filter(d=>d.mood).length}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();document.querySelector('#calendar-month').textContent=new Date(y,m,1).toLocaleDateString('es-CL',{month:'long',year:'numeric'});let html='<span></span>'.repeat((new Date(y,m,1).getDay()+6)%7);for(let n=1;n<=new Date(y,m+1,0).getDate();n++){const k=AyunCore.dateKey(new Date(y,m,n));const r=state.days[k];const c=AyunCore.completedCount(r);html+=`<button class="calendar-day ${c===6?'won':c>0?'partial':''} ${k===currentDate?'today':''} ${k===selectedCalendarDate?'selected':''}" data-date="${k}">${n}</button>`}document.querySelector('#calendar-grid').innerHTML=html;document.querySelectorAll('.calendar-day').forEach(btn=>btn.addEventListener('click',()=>{selectedCalendarDate=btn.dataset.date;renderCalendar();renderDayDetail(selectedCalendarDate)}))}
function renderDayDetail(key){const el=document.querySelector('#day-detail'),r=state.days[key];if(!r){el.innerHTML='<p>Sin registro para este día.</p>';return}el.innerHTML=`<h3>${AyunCore.parseDate(key).toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'})} · ${AyunCore.completedCount(r)}/6</h3><div class="detail-list">${HABITS.map(h=>`<span class="${r.habits[h.id]?'done':''}">${r.habits[h.id]?'♥':'♡'} ${h.name}</span>`).join('')}</div><p>Movimiento: ${r.trainings.length?r.trainings.map(id=>TRAININGS.find(t=>t.id===id)?.name).join(', '):'sin sesión'}<br>Alimentación: ${r.food||'sin registro'} · Ánimo: ${r.mood||'—'}/5</p>${r.moodNote?`<p>Nota: ${escapeHtml(r.moodNote)}</p>`:''}${r.reflection?`<p>Bitácora: ${escapeHtml(r.reflection)}</p>`:''}`}
function renderAll(){renderToday();renderProgress();renderCalendar()}
function bind(){document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#view-${btn.dataset.view}`).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n===btn));window.scrollTo({top:0,behavior:'smooth'})}));document.querySelector('#undo-button').addEventListener('click',()=>{if(!undoSnapshot)return;state=undoSnapshot;undoSnapshot=null;save();renderAll();document.querySelector('#toast').classList.remove('show')});document.querySelectorAll('[data-food]').forEach(btn=>btn.addEventListener('click',()=>withUndo('Registro actualizado',()=>{day().food=day().food===btn.dataset.food?null:btn.dataset.food})));document.querySelectorAll('[data-mood]').forEach(btn=>btn.addEventListener('click',()=>withUndo('Ánimo registrado',()=>{const n=Number(btn.dataset.mood);day().mood=day().mood===n?null:n})));document.querySelector('#mood-note').addEventListener('input',e=>{day().moodNote=e.target.value.slice(0,300);save()});document.querySelector('#reflection').addEventListener('input',e=>{day().reflection=e.target.value.slice(0,600);save()});document.querySelector('#prev-month').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()});document.querySelector('#next-month').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()});document.querySelector('#export-json').addEventListener('click',exportJson);document.querySelector('#export-csv').addEventListener('click',exportCsv);document.querySelector('#import-json').addEventListener('change',importJson);document.querySelector('#reset-today').addEventListener('click',()=>{if(confirm('¿Reiniciar solo el registro de hoy?')){state.days[currentDate]=AyunCore.emptyDay();save();renderAll()}});document.querySelector('#reset-all').addEventListener('click',()=>{if(confirm('Esto borrará todo el progreso de Ayün en este dispositivo. ¿Continuar?')){localStorage.removeItem(STORAGE_KEY);state=emptyState();save();renderAll()}});document.querySelector('#apply-update').addEventListener('click',()=>pendingWorker?.postMessage({type:'SKIP_WAITING'}))}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJson(){state.meta.lastBackupAt=new Date().toISOString();save();download(`ayun-backup-${currentDate}.json`,JSON.stringify(state,null,2),'application/json');showToast('Respaldo creado')}
function exportCsv(){const rows=[['fecha',...AyunCore.HABITS,'bicicleta','fuerza','alimentacion','animo','nota_animo','reflexion']];Object.keys(state.days).sort().forEach(k=>{const r=state.days[k];rows.push([k,...AyunCore.HABITS.map(id=>r.habits[id]?1:0),r.trainings.includes('bike')?1:0,r.trainings.includes('strength')?1:0,r.food||'',r.mood||'',r.moodNote||'',r.reflection||''])});const csv=rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');download(`ayun-${currentDate}.csv`,csv,'text/csv;charset=utf-8')}
function importJson(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result);const clean=emptyState();Object.entries(raw.days||{}).forEach(([k,v])=>{if(/^\d{4}-\d{2}-\d{2}$/.test(k))clean.days[k]=AyunCore.normalizeDay(v)});state=clean;save();renderAll();showToast('Respaldo importado')}catch{alert('No pude leer ese respaldo.')}};reader.readAsText(file);e.target.value=''}
function registerSW(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');const show=w=>{pendingWorker=w;document.querySelector('#update-banner').hidden=false};if(reg.waiting)show(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)show(w)})});let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;window.location.reload()})}catch(err){console.warn('SW',err)}})}
function detectDate(){const next=AyunCore.dateKey();if(next!==currentDate){currentDate=next;renderAll()}}
bind();state.meta.lastOpened=currentDate;save();renderAll();registerSW();setInterval(detectDate,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)detectDate()});
